### ISSUE TITLE
Blacklist for all Items from a Said mod

### ISSUE THREAD

**Issue by ghost** [bl4ckscor3/ChanceGlobe#1]
Hi, I am wondering is there away to black list a single mod from Chance Globes cause I guess someone has been testing the mod with say Biblocraft and it crashes, so I need to black list the whole mod from Chance Globe

**Comment by bl4ckscor3** [comment]
No, there is not. Please try to reproduce the crash and open a seperate issue so I can try and fix it!

EDIT: I can add a configuration option for that, but I have to see how I want the semantics for that to be.

**Comment by bl4ckscor3** [comment]
Added a configuration option for filtering by mod id in c476ce1a5d00cdc4746eaacd235991155fe1536e.
