### ISSUE TITLE
server crash 1.15.2[forge-31.1.16] chanceglobe-1.15.2-v1.3.2

### ISSUE THREAD

**Issue by SDUBZ** [bl4ckscor3/ChanceGlobe#11]
Forge: 31.1.16
chanceglobe-1.15.2-v1.3.2

crash report:
[crash-2020-03-03_22.11.20-server.txt](https://github.com/bl4ckscor3/ChanceGlobe/files/4284905/crash-2020-03-03_22.11.20-server.txt)

logs:
[debug.log](https://github.com/bl4ckscor3/ChanceGlobe/files/4284901/debug.log)

[latest.log](https://github.com/bl4ckscor3/ChanceGlobe/files/4284902/latest.log)

**Comment by bl4ckscor3** [comment]
This is a strange crash. It isn't caused by my code, because I just simply clear a list, but the list tries to remove an element that isn't there. I cannot reproduce this crash either. What does your `chanceglobe-common.toml` config file look like?

**Comment by SDUBZ** [comment]
client
http://puu.sh/Fh3aQ/278a42c2fa.toml
server
http://puu.sh/Fh3bM/45388ed043.toml

**Comment by bl4ckscor3** [comment]
The server link cannot be found.

**Comment by SDUBZ** [comment]
[chanceglobe-common.txt](https://github.com/bl4ckscor3/ChanceGlobe/files/4290638/chanceglobe-common.txt)

**Comment by bl4ckscor3** [comment]
Ok, that's just the default config file. So it's not that. Does the crash happen every time you start the server? Does it also happen on Forge 31.1.14 or 31.1.18? Which Java version are you using?

**Comment by SDUBZ** [comment]
java 8 and forge 31.1.16
yes it was happening every launch
onyl way to stop was to delet configs but after another restart it would bug out again

**Comment by bl4ckscor3** [comment]
Does it also happen on Forge 31.1.14 or 31.1.18?

**Comment by SDUBZ** [comment]
i can trun those other versions due to other mods incompat or using newer versions then .14

**Comment by bl4ckscor3** [comment]
Alright. I still couldn't reproduce the issue, but maybe the beta I just uploaded on CurseForge fixes your problem. Please report back whether it does so or not.

**Comment by SDUBZ** [comment]
will do testing tomorrow

**Comment by bl4ckscor3** [comment]
Since I did not get a reply back, I'm assuming that this is fixed.
