### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kasia1403** [bl4ckscor3/ChanceGlobe#14]
Could You make that this mod ( for Minecraft 1.12.2 ) will load faster and that it will not make javaw.exe (not responding) when Minecraft is loading ? Or do You know universal fix for javaw.exe ( not responding ) ?

**Comment by bl4ckscor3** [comment]
No idea, I no longer support 1.12.2.

**Comment by Kasia1403** [comment]
Are You all modders mean to me or why almost all mods losing support for Minecraft 1.12.2 ? I don't like that !

**Comment by bl4ckscor3** [comment]
Nobody is specifically mean to you. Modders do this in their free time and only have so much time to dedicate to creating their mods, which they rather spend on new versions rather than very old ones like Minecraft 1.12.2.
