### ISSUE TITLE
SecurityCraft issues

### ISSUE THREAD

**Issue by ghost** [bl4ckscor3/ChanceGlobe#2]
When spawned in by ChanceGlobes, ownership is not assigned and become a fixed entity that cannot be removed by the player, I would not know how to test for this one.

**Comment by bl4ckscor3** [comment]
I am aware of that, however I cannot do anything about it as the SecurityCraft block does not have a way of knowing who placed down the Chance Globe. However, you can turn on the config option "Allow claiming unowned blocks?" in SecurityCraft. That way, players can rightclick the unassigned block with a Universal Key Changer that has been renamed to their name and claim the block.
