### ISSUE TITLE
Crash when trying to display Forestry leaves

### ISSUE THREAD

**Issue by MasterSloth1** [bl4ckscor3/ChanceGlobe#3]
so i was popping open some chance globes when my game crashed, I have this thing in the mod pack where it tells you what crashed the game and it pops up with forestry and chance globes. it generated a crash log so here it is :D 

https://gist.github.com/MasterSloth1/50a193ea296310f53a42980e29fe5707

Forge version - 14.23.5.2808
chance globes - 1.12.2-v1.2
forestry - 1.12.2-5.8.2.387
optifine installed
no resource pack

**Comment by bl4ckscor3** [comment]
That's not world breaking at all. Your Chance Globe tried to display an item that Forestry didn't allow to display, so Forestry crashed the game. Your world is fine. I don't know whether I can fix this, but for now just exclude Forestry in the mod exclusion list.

**Comment by MasterSloth1** [comment]
my world is gone upon crashing it had removed my level.dat file, but yea thanks ill add it to the excluded list, should i pop over to forestrys github and paste the same thing there???

**Comment by bl4ckscor3** [comment]
No, Forestry is not the culprit here. If anything, I need to fix it on my end. My mod was not the reason your level.dat file was removed, I just recreated the crash locally and my test world is still there.

**Comment by MasterSloth1** [comment]
hmm interesting i wonder what done it then because when i looked in the save folder for the world it was almost empty a couple of folders is all that was in there

**Comment by MasterSloth1** [comment]
thanks anyways i hope u get it sorted 😄

**Comment by bl4ckscor3** [comment]
I'm no longer supporting the 1.12.2 version of Chance Globe. If you can recreate the issue on 1.14/1.15 versions of Forestry, feel free to reopen and update this issue with the new log/version info..
