### ISSUE TITLE
Unknown error after trying to spawn over 50 globes all at once. which i hoped it would work. it works a few times

### ISSUE THREAD

**Issue by crotin1111** [bl4ckscor3/ChanceGlobe#8]
Unknown error after trying to spawn over 50 globes all at once. which i hoped it would work. it works a few times. my world wont load at all anymore. i dont understand. there is no error log left behind. i have tested with 2 worlds. keeps happening. my world is still in my saves, but when i load the game crashes instantly. any fix or cooldown maybe?

**Comment by crotin1111** [comment]
Edit. Latest version for 1.14.4*

**Comment by bl4ckscor3** [comment]
If the game crashes instantly, there must be some sort of crash report left over in the crash-report folder, or in the latest.log file. Can you send that over, please?

**Comment by crotin1111** [comment]
sure sure
here you go
[crash-2020-01-24_00.36.58-server.txt](https://github.com/bl4ckscor3/ChanceGlobe/files/4109612/crash-2020-01-24_00.36.58-server.txt)

**Comment by crotin1111** [comment]
[crash-2020-01-23_22.17.10-server.txt](https://github.com/bl4ckscor3/ChanceGlobe/files/4109626/crash-2020-01-23_22.17.10-server.txt)

**Comment by crotin1111** [comment]
[crash-2020-01-23_22.04.44-server.txt](https://github.com/bl4ckscor3/ChanceGlobe/files/4109640/crash-2020-01-23_22.04.44-server.txt)

**Comment by crotin1111** [comment]
seems like it could be omega craft not accepting certain item... i will delete omega craft temporary and wait for your reply

**Comment by crotin1111** [comment]
Deleted omega craft.. loads properly now. You could maybe put auto whitelist on how it breaks on omega craft

**Comment by bl4ckscor3** [comment]
There's a reason for the modid blacklist. Just add `omegacraft` to it and it's all fine. I will not add a mod by default, because if in a newer verson of the mod the issue no longer occurs, then I have to update Chance Globe again just to remove the mod from the list, which would readd the issue for people who have not updated to the newest version of the incompatible mod.

**Comment by crotin1111** [comment]
I have deleted the mod due to extreme lag spike, it has not happened since. but i will see for the next updates!
