### ISSUE TITLE
 1.15.2-1.3.1 crashes dedicated server Forge 1.15.2 build 30.0.14

### ISSUE THREAD

**Issue by kreezxil** [bl4ckscor3/ChanceGlobe#9]
Issue:  1.15.2-1.3.1 crashes dedicated server Forge 1.15.2 build 30.0.14

Notes:

crash report:
http://paste.ubuntu.com/p/bgMVPmVq68/

fml server latest:
http://paste.ubuntu.com/p/9sR4tbXM4g/

**Comment by bl4ckscor3** [comment]
I cannot reproduce it with only Chance Globe installed, but I've uploaded a beta of version 1.3.2 with a fix. Please report back if you experience any odd behavior, and if not, I'll remove the beta status of the file and consider this fixed.

**Comment by kreezxil** [comment]
ok, I put it on the server, and we're not crashing now. thank you.
